from django.urls import path
from . import views
from .views import (
    register, custom_login_view, home, lobby, create_game, game_room, profile, 
    request_credits, credit_requests_list, process_request, buy_card, 
    start_game, toggle_auto_call, message_list_api, send_message_api, 
    unread_count_api, mark_conversation_read_api, messaging, create_raffle, 
    raffle_lobby, raffle_detail, percentage_settings, transaction_history, 
    draw_raffle, request_withdrawal, withdrawal_requests, all_withdrawal_requests, 
    process_withdrawal, call_number, payment_methods_list, create_payment_method, 
    edit_payment_method, delete_payment_method, toggle_payment_method, 
    notifications, mark_notification_as_read, delete_notification, 
    block_user, unblock_user, user_management, mark_as_read, 
    buy_multiple_tickets, set_manual_raffle_winner, manage_printable_cards, 
    generate_printable_cards, assign_printable_card, activate_printable_card, 
    print_printable_card, organizer_printable_cards, print_selected_cards, 
    bulk_assign_printable_cards, create_promotion, manage_announcements, 
    edit_announcement, delete_announcement, admin_dashboard, reset_dashboards,
    organizer_dashboard, privacy_policy, terms_of_service, data_deletion, 
    user_manual, launch_promotions, claim_promotion, referral_system, 
    system_health_dashboard, reset_error_counters, get_agora_token, get_token, 
    video_lobby, video_groups_api, verify_video_room_password, 
    delete_video_group, videocall_room, create_videocall, my_bingo_tickets, 
    daily_bingo_schedule, join_daily_bingo, admin_ticket_settings, 
    admin_daily_schedule, admin_ticket_stats, videocall_popup
)

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.custom_login_view, name='login'),
    path('lobby/', views.lobby, name='lobby'),
    path('game/new/', views.create_game, name='create_game'),
    path('game/<int:game_id>/', views.game_room, name='game_room'),
    path('game/<int:game_id>/edit/', views.edit_game_config, name='edit_game_config'),
    path('profile/', views.profile, name='profile'),
    path('credits/request/', views.request_credits, name='request_credits'),
    path('admin-panel/credit-requests/', views.credit_requests_list, name='credit_requests_list'),
    path('admin-panel/process-request/<int:request_id>/', views.process_request, name='process_request'),
    path('game/<int:game_id>/buy_card/', views.buy_card, name='buy_card'),
    path('start-game/<int:game_id>/', views.start_game, name='start_game'),
    path('toggle-auto-call/<int:game_id>/', views.toggle_auto_call, name='toggle_auto_call'),
    path('game/<int:game_id>/toggle-player-marking/', views.toggle_player_marking, name='toggle_player_marking'),
    path('game/<int:game_id>/update-marked-numbers/', views.update_marked_numbers, name='update_marked_numbers'),
    path('game/<int:game_id>/mark-number/', views.mark_number, name='mark_number'),
    path('api/messages/', views.message_list_api, name='message_list_api'),
    path('api/messages/send/', views.send_message_api, name='send_message_api'),
    path('api/unread-count/', views.unread_count_api, name='unread_count_api'),
    path('api/mark-read/', views.mark_conversation_read_api, name='mark_conversation_read_api'),
    path('messaging/', views.messaging, name='messaging'),
    path('raffle/new/', views.create_raffle, name='create_raffle'),
    path('raffles/', views.raffle_lobby, name='raffle_lobby'),
    path('raffle/<int:raffle_id>/', views.raffle_detail, name='raffle_detail'),
    path('admin-panel/settings/', views.percentage_settings, name='percentage_settings'),
    path('admin-panel/transactions/', views.transaction_history, name='transaction_history'),
    path('admin-panel/transactions/user/<int:user_id>/', views.transaction_history, name='transaction_history_user'),
    path('raffle/<int:raffle_id>/draw/', views.draw_raffle, name='draw_raffle'),
    path('withdraw/', views.request_withdrawal, name='request_withdrawal'),
    path('admin-panel/withdrawals/', views.withdrawal_requests, name='withdrawal_requests'),
    path('admin-panel/withdrawals/all/', views.all_withdrawal_requests, name='all_withdrawal_requests'),
    path('admin-panel/withdrawals/process/<int:request_id>/', views.process_withdrawal, name='process_withdrawal'),
    path('game/<int:game_id>/call-number/', views.call_number, name='call_number'),
    path('admin-panel/payment-methods/', views.payment_methods_list, name='payment_methods_list'),
    path('admin-panel/payment-methods/create/', views.create_payment_method, name='create_payment_method'),
    path('admin-panel/payment-methods/edit/<int:method_id>/', views.edit_payment_method, name='edit_payment_method'),
    path('admin-panel/payment-methods/delete/<int:method_id>/', views.delete_payment_method, name='delete_payment_method'),
    path('admin-panel/payment-methods/toggle/<int:method_id>/', views.toggle_payment_method, name='toggle_payment_method'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/mark-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('admin-panel/users/block/<int:user_id>/', views.block_user, name='block_user'),
    path('admin-panel/users/unblock/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('admin-panel/users/', views.user_management, name='user_management'),
    path('notifications/mark-as-read/', views.mark_as_read, name='mark_as_read'),
    path('raffle/<int:raffle_id>/buy-multiple/', views.buy_multiple_tickets, name='buy_multiple_tickets'),
    path('raffle/<int:raffle_id>/set-manual-winner/', views.set_manual_raffle_winner, name='set_manual_raffle_winner'),
    path('admin-panel/printable-cards/', views.manage_printable_cards, name='manage_printable_cards'),
    path('admin-panel/printable-cards/generate/', views.generate_printable_cards, name='generate_printable_cards'),
    path('admin-panel/printable-cards/assign/<str:card_id>/', views.assign_printable_card, name='assign_printable_card'),
    path('game/<int:game_id>/activate-card/', views.activate_printable_card, name='activate_printable_card'),
    path('printable-card/<str:card_id>/print/', views.print_printable_card, name='print_printable_card'),
    path('organizer/printable-cards/', views.organizer_printable_cards, name='organizer_printable_cards'),
    path('organizer/print-selected-cards/', views.print_selected_cards, name='print_selected_cards'),
    path('admin-panel/bulk-assign-cards/', views.bulk_assign_printable_cards, name='bulk_assign_printable_cards'),
    path('promotions/create/', views.create_promotion, name='create_promotion'),
    path('admin-panel/announcements/', views.manage_announcements, name='manage_announcements'),
    path('admin-panel/announcements/edit/<int:announcement_id>/', views.edit_announcement, name='edit_announcement'),
    path('admin-panel/announcements/delete/<int:announcement_id>/', views.delete_announcement, name='delete_announcement'),
    path('admin-panel/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/dashboard/reset/', views.reset_dashboards, name='reset_dashboards'),
    path('organizer/dashboard/', views.organizer_dashboard, name='organizer_dashboard'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('data-deletion/', views.data_deletion, name='data_deletion'),
    path('manual/', views.user_manual, name='user_manual'),
    path('promotions/', views.launch_promotions, name='launch_promotions'),
    path('promotions/claim/<int:promotion_id>/', views.claim_promotion, name='claim_promotion'),
    path('referral-system/', views.referral_system, name='referral_system'),
    path('system-health/', views.system_health_dashboard, name='system_health_dashboard'),
    path('reset-errors/', views.reset_error_counters, name='reset_error_counters'),
    path('api/get-agora-token/', views.get_agora_token, name='get_agora_token'),
    path('api/get_token/', views.get_token, name='get_token'),
    path('video/lobby/', views.video_lobby, name='video_lobby'),
    path('video/create/', views.create_videocall, name='create_videocall'),
    path('video/room/<int:group_id>/', views.videocall_room, name='videocall_room'),
    path('api/videocallgroups/', views.video_groups_api, name='video_groups_api'),
    path('api/video-groups/<int:group_id>/verify-password/', views.verify_video_room_password, name='verify_video_room_password'),
    path('api/video-groups/<int:group_id>/delete/', views.delete_video_group, name='delete_video_group'),
    path('tickets/', views.my_bingo_tickets, name='my_bingo_tickets'),
    path('daily-bingo/', views.daily_bingo_schedule, name='daily_bingo_schedule'),
    path('daily-bingo/join/<int:schedule_id>/', views.join_daily_bingo, name='join_daily_bingo'),
    path('admin-panel/tickets/settings/', views.admin_ticket_settings, name='admin_ticket_settings'),
    path('admin-panel/tickets/schedule/', views.admin_daily_schedule, name='admin_daily_schedule'),
    path('admin-panel/tickets/stats/', views.admin_ticket_stats, name='admin_ticket_stats'),
    path('videocall-popup/', views.videocall_popup, name='videocall_popup'),
    # IA Assistant endpoints
    path('admin-panel/ai/chatbot/', views.ai_chatbot_api, name='ai_chatbot_api'),
    path('admin-panel/ai/report/', views.ai_generate_report, name='ai_generate_report'),
    path('admin-panel/ai/analysis/', views.ai_analysis_api, name='ai_analysis_api'),
    # Test email endpoint
    path('admin-panel/test-email/', views.test_email_view, name='test_email_view'),
    # Cuentas por Cobrar
    path('admin-panel/accounts-receivable/', views.admin_accounts_receivable, name='admin_accounts_receivable'),
    path('organizer/accounts-receivable/', views.organizer_accounts_receivable, name='organizer_accounts_receivable'),
    path('organizer/accounts-receivable/create/', views.create_account_receivable, name='create_account_receivable'),
    path('organizer/accounts-receivable/<int:account_id>/', views.account_receivable_detail, name='account_receivable_detail'),
    path('organizer/accounts-receivable/<int:account_id>/add-payment/', views.add_payment_to_account, name='add_payment_to_account'),
    # Sistema de Franquicias - Configuración de Precios
    path('admin-panel/package-prices/', views.edit_package_prices, name='edit_package_prices'),
    path('admin-panel/package-prices/reset/', views.reset_package_prices, name='reset_package_prices'),
    # Sistema de Franquicias - Gestión (Super Admin)
    path('admin-panel/franchises/', views.franchise_list, name='franchise_list'),
    path('admin-panel/franchises/create/', views.franchise_create, name='franchise_create'),
    path('admin-panel/franchises/<int:franchise_id>/', views.franchise_detail, name='franchise_detail'),
    path('admin-panel/franchises/<int:franchise_id>/edit/', views.franchise_edit, name='franchise_edit'),
    path('admin-panel/franchises/<int:franchise_id>/change-image/', views.franchise_change_image, name='franchise_change_image'),
    # Sistema de Franquicias - Panel para Franquiciado
    # IMPORTANTE: Estas URLs deben estar ANTES de la URL genérica franchise/<slug>/
    path('franchise/dashboard/', views.franchise_owner_dashboard, name='franchise_owner_dashboard'),
    path('franchise/credit-requests/', views.franchise_owner_credit_requests, name='franchise_owner_credit_requests'),
    path('franchise/credit-requests/<int:request_id>/process/', views.franchise_owner_process_credit, name='franchise_owner_process_credit'),
    path('franchise/withdrawal-requests/', views.franchise_owner_withdrawal_requests, name='franchise_owner_withdrawal_requests'),
    path('franchise/withdrawal-requests/<int:request_id>/process/', views.franchise_owner_process_withdrawal, name='franchise_owner_process_withdrawal'),
    # Gestión de Cuentas Bancarias para Propietarios de Franquicia
    path('franchise/bank-accounts/', views.franchise_owner_bank_accounts, name='franchise_owner_bank_accounts'),
    path('franchise/bank-accounts/create/', views.franchise_owner_create_bank_account, name='franchise_owner_create_bank_account'),
    path('franchise/bank-accounts/<int:account_id>/edit/', views.franchise_owner_edit_bank_account, name='franchise_owner_edit_bank_account'),
    path('franchise/bank-accounts/<int:account_id>/delete/', views.franchise_owner_delete_bank_account, name='franchise_owner_delete_bank_account'),
    path('franchise/bank-accounts/<int:account_id>/toggle/', views.franchise_owner_toggle_bank_account, name='franchise_owner_toggle_bank_account'),
    # Landing de franquicia (DEBE estar al final para no capturar rutas específicas)
    path('franchise/<slug:franchise_slug>/', views.franchise_landing, name='franchise_landing'),
]


# Configuración para manejo de errores
handler404 = 'bingo_app.views.handler404'
handler500 = 'bingo_app.views.handler500'