'''
Django settings for bingo_project project.

Generated by 'django-admin startproject' using Django 5.2.2.
# Force rebuild 2025-10-14 - Fix curly quotes

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''

from pathlib import Path
import os
import urllib.parse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# Sentry Configuration
SENTRY_DSN = os.environ.get("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
        ],
        traces_sample_rate=1.0,
        profiles_sample_rate=1.0,
        send_default_pii=True,
    )

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-key-CHANGE-IN-PRODUCTION-EZrZy3Gxp5SMCD8QBYBslMa1Tsns6WvcJlOgtgk5Wc4802zhGhPuhlmGn8Gas8L2jXo")
# ⚠️ IMPORTANTE: En producción (Railway), DEBES configurar SECRET_KEY en las variables de entorno

CSRF_TRUSTED_ORIGINS = ['https://*.railway.app', 'https://web-production-2d504.up.railway.app']

# Configuración de seguridad SSL/HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURITY WARNING: don't run with debug turned on in production!
# Configuración de DEBUG para producción
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Forzar DEBUG = False en producción (Railway)
if 'railway.app' in os.environ.get('ALLOWED_HOSTS', '') or os.environ.get('RAILWAY_ENVIRONMENT'):
    DEBUG = False

# SOLUCIÓN DIRECTA: Forzar DEBUG = False en producción
# Si no funciona la detección automática, descomenta la línea siguiente:
# DEBUG = False  # ⚠️ Comentado temporalmente para desarrollo local

# Solo redirigir a HTTPS en producción
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Advertir si se usa SECRET_KEY de desarrollo en producción
if SECRET_KEY.startswith('django-insecure-dev-key'):
    railway_env = os.environ.get('RAILWAY_ENVIRONMENT')
    if railway_env:  # Solo validar si está en Railway
        raise ValueError(
            "❌ ERROR DE SEGURIDAD: Estás ejecutando en Railway con SECRET_KEY de desarrollo. "
            "Configúrala con: railway variables set SECRET_KEY='[clave-segura-aqui]' "
            "Genera una con: python -c 'import secrets; print(secrets.token_urlsafe(50))'"
        )
    # En local, solo advertir
    import sys
    sys.stderr.write("WARNING: Usando SECRET_KEY de desarrollo. Cambiar antes de produccion.\n")

# Cache busting para forzar actualización de archivos estáticos
CACHE_BUST = os.environ.get('CACHE_BUST', 'final_test_002')

# Configuración de Cache para mejor rendimiento
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Configuración de logging mejorada (solo consola para Railway)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'bingo_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'error_monitor': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

AUTH_USER_MODEL = 'bingo_app.User'
# Application definition

LOGIN_URL = 'login'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'bingo_app',

    # allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'

SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_FIELDS = ('username', 'email')

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_SECRET'),
            'key': ''
        }
    },
    'facebook': {
        'APP': {
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID'),
            'secret': os.environ.get('FACEBOOK_SECRET'),
            'key': ''
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'es_ES',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v18.0',
    }
}

# Agora Credentials
AGORA_APP_ID = os.environ.get('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = os.environ.get('AGORA_APP_CERTIFICATE')

ASGI_APPLICATION = 'bingo_project.asgi.application'

redis_url = os.environ.get("REDIS_URL")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [redis_url],  # 👈 Usa la URL completa (con auth)
        },
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'bingo_app.middleware.FranchiseMiddleware',  # Middleware para detectar franquicia
    'bingo_app.middleware.FlashMessageMiddleware',  # Middleware para mensajes flash
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bingo_app.middleware.FlashMessageMiddleware',
]

ROOT_URLCONF = 'bingo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bingo_app.context_processors.notifications_global',
                'bingo_app.context_processors.announcements_processor',
                'bingo_app.context_processors.system_settings_processor',
                'bingo_app.context_processors.franchise_processor',
            ],
        },

    },
]

#WSGI_APPLICATION = 'bingo_project.wsgi.application'

import dj_database_url

# ============================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================
# En desarrollo: Si no hay DATABASE_URL, usa SQLite local
# En producción: Usa DATABASE_URL de Railway
# ============================================

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Producción o desarrollo con PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL, 
            conn_health_checks=True
        )
    }
else:
    # Desarrollo local con SQLite (SEGURO - no toca producción)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_desarrollo.sqlite3',  # Nombre diferente para evitar confusiones
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # o cualquier carpeta donde guardes los uploads


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
  #  os.path.join(BASE_DIR, 'static'),  # carpeta donde están tus archivos estáticos durante desarrollo
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # carpeta donde Django los recolectará para producción

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# Allauth settings for email
ACCOUNT_LOGIN_METHODS = ['email']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Bingo App] '
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SOCIALACCOUNT_ADAPTER = 'bingo_app.adapters.CustomSocialAccountAdapter'

# Trigger new deployment