# Generated by Django 5.2.2 on 2025-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0002_flashmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='initial_cards_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Cartones vendidos al inicio'),
        ),
    ]
