# Generated by Django 5.2.2 on 2025-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0003_game_initial_cards_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='initial_cards_sold',
        ),
        migrations.AddField(
            model_name='game',
            name='max_cards_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Máximo cartones vendidos'),
        ),
    ]
