# Generated by Django 5.2.2 on 2025-08-06 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0004_remove_game_initial_cards_sold_game_max_cards_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='custom_pattern',
            field=models.JSONField(blank=True, help_text='Matriz 5x5 que representa el patrón personalizado (1=casilla requerida, 0=no requerida)', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='base_prize',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Premio base'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_price',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Precio por cartón'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_prize',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='Premio actual'),
        ),
        migrations.AlterField(
            model_name='game',
            name='entry_price',
            field=models.DecimalField(decimal_places=5, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Precio de entrada'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_pattern',
            field=models.CharField(choices=[('HORIZONTAL', 'Línea horizontal'), ('VERTICAL', 'Línea vertical'), ('DIAGONAL', 'Línea diagonal (X)'), ('FULL', 'Tabla llena'), ('CORNERS', 'Cuatro esquinas'), ('CUSTOM', 'Patrón personalizado')], default='FULL', max_length=20),
        ),
    ]
