# Generated by Django 5.2.2 on 2025-08-06 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0005_game_custom_pattern_alter_game_base_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='base_prize',
            field=models.PositiveIntegerField(default=0, verbose_name='Premio base'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Precio por cartón'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_prize',
            field=models.PositiveIntegerField(default=0, verbose_name='Premio actual'),
        ),
        migrations.AlterField(
            model_name='game',
            name='entry_price',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio de entrada'),
        ),
    ]
