# Generated by Django 5.2.2 on 2025-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0007_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Banco de Venezuela, Zelle, PayPal, Binance, etc.', max_length=100, verbose_name='Título/Nombre')),
                ('details', models.TextField(help_text='Información completa que verán los usuarios. Ej: Número de cuenta, titular, cédula, teléfono, email, etc.', verbose_name='Detalles completos')),
                ('instructions', models.TextField(blank=True, help_text='Instrucciones específicas para este método (opcional)', verbose_name='Instrucciones especiales')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar este método a los usuarios', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (mayor número = más arriba)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['-order', 'title'],
            },
        ),
    ]
