# Generated by Django 5.2.2 on 2025-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0008_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_manual_winner',
            field=models.BooleanField(default=False, verbose_name='Selección manual de ganador'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='manual_winning_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número ganador manual'),
        ),
    ]
