# Generated by Django 5.2.2 on 2025-08-18 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0011_user_block_reason_user_blocked_at_user_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagesettings',
            name='entry_commission',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión por creación de juego (%)'),
        ),
    ]
