# Generated by Django 5.2.2 on 2025-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0012_percentagesettings_entry_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='proof_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal_proofs/'),
        ),
    ]
