# Generated by Django 5.2.2 on 2025-08-25 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0013_add_proof_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The CreateModel operation was here, but it has been removed
        # because the table already exists in the production database.
        # This allows the migration to be marked as "run" without erroring.
    ]
