# Generated by Django 5.2.2 on 2025-08-27 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0014_withdrawalrequestnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='is_manual_winner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        
    ]
