# Generated by Django 5.2.2 on 2025-08-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0016_printablecard_withdrawalrequestnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allows_printable_cards',
            field=models.BooleanField(default=False, verbose_name='Permitir cartones imprimibles'),
        ),
    ]
