# Generated by Gemini

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0017_game_allows_printable_cards_and_more'),
    ]

    operations = [
    ]