# Generated by Django 5.2.2 on 2025-08-31 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0018_add_allows_printable_cards_to_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percentagesettings',
            options={'verbose_name_plural': 'Configuración de Comisiones'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_prize',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_prize_target',
        ),
        migrations.RemoveField(
            model_name='percentagesettings',
            name='admin_percentage',
        ),
        migrations.RemoveField(
            model_name='percentagesettings',
            name='entry_commission',
        ),
        migrations.RemoveField(
            model_name='percentagesettings',
            name='organizer_percentage',
        ),
        migrations.RemoveField(
            model_name='percentagesettings',
            name='player_percentage',
        ),
        migrations.AddField(
            model_name='game',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Bloqueado'),
        ),
        migrations.AddField(
            model_name='game',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Premio Fijo'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Comisión que la plataforma cobra al organizador sobre los ingresos totales (venta de cartones/tickets).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='raffle',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Bloqueado'),
        ),
        migrations.AlterField(
            model_name='game',
            name='base_prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='progressive_prizes',
            field=models.JSONField(default=list),
        ),
    ]