# Generated by Django 5.2.2 on 2025-09-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0019_alter_percentagesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_completed_events',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
