# Generated by Django 5.2.2 on 2025-09-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0020_user_reputation_score_user_total_completed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Compra de cartones'), ('ADMIN_ADD', 'Recarga administrativa'), ('PRIZE', 'Premio de juego'), ('GAME_CREATION_FEE', 'Tarifa de creación de juego'), ('RAFFLE_CREATION_FEE', 'Tarifa de creación de rifa'), ('PRIZE_LOCK', 'Bloqueo de premio'), ('PRIZE_UNLOCK', 'Desbloqueo de premio'), ('ORGANIZER_REVENUE', 'Ingresos del organizador'), ('PLATFORM_COMMISSION', 'Comisión de la plataforma'), ('WITHDRAWAL', 'Retiro de créditos'), ('WITHDRAWAL_REFUND', 'Reembolso de retiro'), ('OTHER', 'Otra transacción')], default='PURCHASE', max_length=20),
        ),
    ]
