# Generated by Django 5.2.2 on 2025-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0021_user_blocked_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reputation_score',
        ),
        migrations.AddField(
            model_name='user',
            name='manual_reputation',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino'), ('LEYENDA', 'Leyenda')], default='AUTO', help_text='Permite a un admin asignar un nivel de reputación manualmente.', max_length=10),
        ),
    ]
