# Generated by Django 5.2.2 on 2025-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0022_add_manual_reputation_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='El texto del anuncio que se mostrará en el carrusel.', max_length=255)),
                ('link', models.URLField(blank=True, help_text='(Opcional) Un enlace al que el usuario irá si hace clic en el anuncio.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Marcar para mostrar este anuncio. Desmarcar para ocultarlo.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (número más bajo primero).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
