# Generated by Django 5.2.2 on 2025-09-10 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def remove_link_field_if_exists(apps, schema_editor):
    """Elimina el campo link solo si existe"""
    db_table = 'bingo_app_announcement'
    with connection.cursor() as cursor:
        # Verificar si la columna existe (depende del tipo de BD)
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name='link'
            """, [db_table])
            if cursor.fetchone():
                cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN link;')
        elif connection.vendor == 'sqlite':
            # SQLite no soporta DROP COLUMN directamente, pero podemos intentar
            # En SQLite, si la columna no existe, simplemente ignoramos el error
            try:
                cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN link;')
            except Exception:
                pass  # La columna no existe, no hay problema


def reverse_remove_link_field(apps, schema_editor):
    """No hacemos nada al revertir"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0023_add_announcement_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Anuncio y Promoción', 'verbose_name_plural': 'Anuncios y Promociones'},
        ),
        # RemoveField con verificación segura
        migrations.RunPython(
            remove_link_field_if_exists,
            reverse_remove_link_field,
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PROMOTION', 'Promoción de Evento'), ('EXTERNAL', 'Anuncio Externo')], default='GENERAL', max_length=10, verbose_name='Tipo de Anuncio'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='El anuncio se ocultará automáticamente después de esta fecha.', null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='external_link',
            field=models.URLField(blank=True, help_text='URL a la que se dirigirá el usuario al hacer clic.', null=True, verbose_name='Enlace Externo'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Sube una imagen para el anuncio.', null=True, upload_to='announcements/', verbose_name='Imagen del Anuncio'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Promocionado por'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='related_game',
            field=models.ForeignKey(blank=True, help_text='Si es una promoción, selecciona el juego.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo_app.game', verbose_name='Juego Relacionado'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='related_raffle',
            field=models.ForeignKey(blank=True, help_text='Si es una promoción, selecciona la rifa.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo_app.raffle', verbose_name='Rifa Relacionada'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, help_text='Opcional. URL de un video para embeber (ej. YouTube, Vimeo).', null=True, verbose_name='URL de Video (Embed)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Marcar para mostrar este anuncio.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.CharField(help_text='El texto principal del anuncio.', max_length=255),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición (número más bajo primero).'),
        ),
    ]
