# Generated by Django 5.2.2 on 2025-09-11 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0024_alter_announcement_options_remove_announcement_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagesettings',
            name='image_promotion_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Costo en créditos para promocionar un evento con una imagen.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Promoción con Imagen'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='video_promotion_price',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Costo en créditos para promocionar un evento con un video.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Promoción con Video'),
        ),
    ]
