# Generated by Django 5.2.2 on 2025-09-24 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0025_percentagesettings_image_promotion_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='bingo_app.bankaccount'),
        ),
    ]
