# Generated by Django 5.2.2 on 2025-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0027_alter_creditrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
