# Generated by Django 5.2.7 on 2025-10-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0028_alter_game_is_finished_alter_game_is_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agora_channel_name', models.CharField(max_length=255, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_call_groups', to='bingo_app.game')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_video_call_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
