# Generated by Django 5.2.7 on 2025-10-10 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0029_videocallgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocallgroup',
            name='game',
        ),
        migrations.AddField(
            model_name='videocallgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_video_call_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocallgroup',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
