# Generated by Django 5.2.7 on 2025-10-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0030_remove_videocallgroup_game_videocallgroup_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallgroup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
