# Generated by Django 5.2.7 on 2025-10-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0031_videocallgroup_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallgroup',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_call_groups', to='bingo_app.game'),
        ),
    ]
