# Generated by Django 5.2.7 on 2025-10-16 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0034_fix_all_missing_user_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagesettings',
            name='game_creation_fee',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Costo fijo en créditos para crear un nuevo juego.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarifa de Creación de Juego'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='game_creation_fee_enabled',
            field=models.BooleanField(default=True, help_text='Activar o desactivar la tarifa de creación de juegos.', verbose_name='Activar Tarifa de Creación'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='platform_commission_enabled',
            field=models.BooleanField(default=True, help_text='Activar o desactivar la comisión sobre ventas de cartones.', verbose_name='Activar Comisión por Cartón'),
        ),
    ]
