# Generated by Django 5.2.7 on 2025-10-19 04:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0038_add_raffle_held_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('achievement_type', models.CharField(choices=[('PIONEER', 'Pionero - Primeros 100 usuarios'), ('FOUNDER', 'Fundador - Usuario del primer día'), ('CHAMPION', 'Campeón Inaugural - Ganador del primer torneo'), ('EARLY_BIRD', 'Madrugador - Primeros 10 usuarios'), ('SOCIAL_BUTTERFLY', 'Mariposa Social - Invitó 5 amigos')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50)),
                ('bonus_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_recipients', models.IntegerField(blank=True, null=True)),
                ('current_recipients', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promotion_type', models.CharField(choices=[('WELCOME_BONUS', 'Bono de Bienvenida'), ('FIRST_DEPOSIT', 'Bono Primer Depósito'), ('REFERRAL_BONUS', 'Bono por Referido'), ('DAILY_BONUS', 'Bono Diario'), ('LAUNCH_SPECIAL', 'Promoción de Lanzamiento')], max_length=20)),
                ('description', models.TextField()),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Máximo número de usos (null = ilimitado)', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('bonus_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo_app.launchachievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo_app.launchpromotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_promotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
