# Generated by Django 5.2.7 on 2025-10-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0039_launchachievement_launchpromotion_referralprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoTicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system_active', models.BooleanField(default=False, help_text='Activar/desactivar todo el sistema de tickets')),
                ('referral_ticket_bonus', models.PositiveIntegerField(default=1, help_text='Tickets que recibe el referidor por cada referido')),
                ('referred_ticket_bonus', models.PositiveIntegerField(default=1, help_text='Tickets que recibe el usuario referido')),
                ('ticket_expiration_days', models.PositiveIntegerField(default=7, help_text='Días hasta que expire un ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tickets',
                'verbose_name_plural': 'Configuración de Tickets',
            },
        ),
        migrations.CreateModel(
            name='DailyBingoSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('14:00', '2:00 PM'), ('19:00', '7:00 PM')], max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Activar/desactivar este horario')),
                ('max_players', models.PositiveIntegerField(default=50, help_text='Máximo número de jugadores')),
                ('prize_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Premio base para este horario', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Descripción del bingo', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time_slot'],
            },
        ),
        migrations.CreateModel(
            name='BingoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('DAILY_MORNING', 'Bingo Matutino (9:00 AM)'), ('DAILY_AFTERNOON', 'Bingo Vespertino (2:00 PM)'), ('DAILY_EVENING', 'Bingo Nocturno (7:00 PM)'), ('REFERRAL', 'Ticket por Referido'), ('PROMOTION', 'Ticket Promocional')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del ticket', null=True)),
                ('used_in_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo_app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
