# Generated by Django 5.2.7 on 2025-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0040_bingoticketsettings_dailybingoschedule_bingoticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percentagesettings',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuración del Sistema'},
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='credits_purchase_enabled',
            field=models.BooleanField(default=True, help_text='Permitir a los usuarios solicitar compra de créditos. Si se desactiva, los usuarios no verán esta opción.', verbose_name='Activar Compra de Créditos'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='credits_withdrawal_enabled',
            field=models.BooleanField(default=True, help_text='Permitir a los usuarios solicitar retiros. Si se desactiva, los usuarios no verán esta opción.', verbose_name='Activar Retiro de Créditos'),
        ),
        migrations.AddField(
            model_name='percentagesettings',
            name='referral_system_enabled',
            field=models.BooleanField(default=True, help_text='Activar o desactivar el sistema de referidos. Si se desactiva, no se mostrarán códigos de referido.', verbose_name='Activar Sistema de Referidos'),
        ),
    ]
