# Generated by Django 5.2.7 on 2025-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0041_add_system_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagesettings',
            name='promotions_enabled',
            field=models.BooleanField(default=True, help_text='Activar o desactivar el sistema de promociones (bonos de bienvenida, promociones especiales, etc.). Si se desactiva, los usuarios no verán las promociones.', verbose_name='Activar Promociones y Bonos'),
        ),
    ]
