# Generated by Django 5.2.7 on 2025-10-22 03:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0042_add_promotions_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Créditos bloqueados por premios. No puede ser negativo.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo de créditos del usuario. No puede ser negativo.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
