# Generated by Django 5.2.7 on 2025-10-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0043_alter_user_blocked_credits_alter_user_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_manual_marking',
            field=models.BooleanField(default=False, help_text='Si True, el jugador marca números manualmente; si False, se marcan automáticamente'),
        ),
    ]
