# Generated by Django 5.2.7 on 2025-10-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0044_player_is_manual_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='marked_numbers',
            field=models.JSONField(default=list, help_text='Números marcados manualmente por el jugador'),
        ),
    ]
