# Generated by Django 5.2.7 on 2025-11-01 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0045_player_marked_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallgroup',
            name='raffle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_call_groups', to='bingo_app.raffle'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ENTRY_FEE', 'Entrada a juego'), ('PURCHASE', 'Compra de cartones'), ('ADMIN_ADD', 'Recarga administrativa'), ('PRIZE', 'Premio de juego'), ('GAME_CREATION_FEE', 'Tarifa de creación de juego'), ('RAFFLE_CREATION_FEE', 'Tarifa de creación de rifa'), ('PRIZE_LOCK', 'Bloqueo de premio'), ('PRIZE_UNLOCK', 'Desbloqueo de premio'), ('ORGANIZER_REVENUE', 'Ingresos del organizador'), ('PLATFORM_COMMISSION', 'Comisión de la plataforma'), ('WITHDRAWAL', 'Retiro de créditos'), ('WITHDRAWAL_REFUND', 'Reembolso de retiro'), ('OTHER', 'Otra transacción')], default='PURCHASE', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocallgroup',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_call_groups', to='bingo_app.game'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game')},
        ),
    ]
