# Generated by Django 5.2.7 on 2025-11-02 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0046_videocallgroup_raffle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallgroup',
            name='active_users',
            field=models.ManyToManyField(blank=True, related_name='active_video_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocallgroup',
            name='is_persistent',
            field=models.BooleanField(default=True, help_text='Si es True, la sala se mantiene activa entre juegos'),
        ),
    ]
