# Generated by Django 5.2.7 on 2025-11-11 00:43

from django.db import migrations, models


def ensure_theme_color(apps, schema_editor):
    connection = schema_editor.connection
    table = 'bingo_app_user'
    column = 'theme_color'
    default = 'classic'

    with connection.cursor() as cursor:
        columns = [col.name for col in connection.introspection.get_table_description(cursor, table)]
        if column not in columns:
            if connection.vendor == 'postgresql':
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN "{column}" varchar(32) NOT NULL DEFAULT %s',
                    [default],
                )
            else:
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN "{column}" varchar(32) NOT NULL DEFAULT \'{default}\''
                )
        # Asegurar que no existan valores nulos
        if connection.vendor == 'sqlite':
            cursor.execute(
                f'UPDATE "{table}" SET "{column}" = \'{default}\' WHERE "{column}" IS NULL'
            )
        else:
            cursor.execute(
                f'UPDATE "{table}" SET "{column}" = %s WHERE "{column}" IS NULL',
                [default],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0049_alter_game_card_price'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_theme_color, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='theme_color',
                    field=models.CharField(
                        blank=True,
                        default='classic',
                        help_text='Preferencia de color del usuario para la interfaz.',
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
