# Generated by Django 5.2.7 on 2025-11-11 01:38

from django.db import migrations, models


def ensure_win_effect(apps, schema_editor):
    connection = schema_editor.connection
    table = 'bingo_app_user'
    column = 'win_effect'
    default = 'confetti'

    with connection.cursor() as cursor:
        columns = [col.name for col in connection.introspection.get_table_description(cursor, table)]
        if column not in columns:
            if connection.vendor == 'postgresql':
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN "{column}" varchar(32) NOT NULL DEFAULT %s',
                    [default],
                )
            else:
                cursor.execute(
                    f'ALTER TABLE "{table}" ADD COLUMN "{column}" varchar(32) NOT NULL DEFAULT \'{default}\''
                )
        if connection.vendor == 'sqlite':
            cursor.execute(
                f'UPDATE "{table}" SET "{column}" = \'{default}\' WHERE "{column}" IS NULL'
            )
        else:
            cursor.execute(
                f'UPDATE "{table}" SET "{column}" = %s WHERE "{column}" IS NULL',
                [default],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0050_user_theme_color'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_win_effect, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='win_effect',
                    field=models.CharField(
                        blank=True,
                        default='confetti',
                        help_text='Efecto visual mostrado cuando el usuario gana.',
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
