# Generated by Django 5.2.7 on 2025-12-03 02:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0051_user_win_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentagesettings',
            name='accounts_receivable_enabled',
            field=models.BooleanField(default=True, help_text='Activar o desactivar el módulo de cuentas por cobrar para organizadores. Si se desactiva, los organizadores no verán esta opción.', verbose_name='Activar Cuentas por Cobrar para Organizadores'),
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total')),
                ('concept', models.TextField(help_text='Descripción del motivo de la deuda', verbose_name='Concepto de la Deuda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Deudor')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts_receivable', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Abono')),
                ('proof', models.FileField(upload_to='accounts_receivable_proofs/', verbose_name='Comprobante de Pago')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bingo_app.accountsreceivable', verbose_name='Cuenta por Cobrar')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_receivable_payments', to='bingo_app.bankaccount', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Pago de Cuenta por Cobrar',
                'verbose_name_plural': 'Pagos de Cuentas por Cobrar',
                'ordering': ['-created_at'],
            },
        ),
    ]
