# Generated by Django 5.2.7 on 2025-12-07 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_link_field_if_exists(apps, schema_editor):
    """
    Elimina el campo 'link' de Announcement solo si existe.
    Esto evita errores si el campo ya fue eliminado en una migración anterior.
    """
    db_alias = schema_editor.connection.alias
    try:
        with schema_editor.connection.cursor() as cursor:
            # Verificar si la columna existe
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='bingo_app_announcement' 
                AND column_name='link'
            """)
            if cursor.fetchone():
                # La columna existe, eliminarla usando SQL directo
                cursor.execute("ALTER TABLE bingo_app_announcement DROP COLUMN IF EXISTS link;")
    except Exception:
        # Si hay algún error, simplemente continuar
        # El campo probablemente ya no existe
        pass


def reverse_remove_link_field(apps, schema_editor):
    """
    Función reversa: no hace nada porque no queremos recrear el campo
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0052_percentagesettings_accounts_receivable_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('BASIC_BINGO', 'Básico Bingo'), ('PRO_BINGO', 'PRO Bingo'), ('BASIC_RAFFLE', 'Básico Rifa'), ('PRO_RAFFLE', 'PRO Rifa')], max_length=20, unique=True, verbose_name='Tipo de Paquete')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('description', models.TextField(help_text='Descripción del paquete', verbose_name='Descripción')),
                ('default_monthly_price', models.DecimalField(decimal_places=2, help_text='Precio mensual por defecto (puedes cambiarlo)', max_digits=10, verbose_name='Precio Mensual por Defecto')),
                ('current_monthly_price', models.DecimalField(decimal_places=2, help_text='Precio mensual actual (el que se usa)', max_digits=10, verbose_name='Precio Mensual Actual')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, help_text='Comisión por defecto (puedes cambiarla)', max_digits=5, verbose_name='Comisión por Defecto (%)')),
                ('current_commission_rate', models.DecimalField(decimal_places=2, help_text='Comisión actual (la que se usa)', max_digits=5, verbose_name='Comisión Actual (%)')),
                ('bingos_enabled', models.BooleanField(default=False, verbose_name='Bingos Habilitado')),
                ('raffles_enabled', models.BooleanField(default=False, verbose_name='Rifas Habilitado')),
                ('accounts_receivable_enabled', models.BooleanField(default=False, verbose_name='Cuentas por Cobrar Habilitado')),
                ('video_calls_bingos_enabled', models.BooleanField(default=False, verbose_name='Video Llamadas (Bingos) Habilitado')),
                ('video_calls_raffles_enabled', models.BooleanField(default=False, verbose_name='Video Llamadas (Rifas) Habilitado')),
                ('custom_manual_enabled', models.BooleanField(default=True, verbose_name='Manual Personalizable Habilitado')),
                ('notifications_push_enabled', models.BooleanField(default=False, verbose_name='Notificaciones Push Habilitado')),
                ('advanced_reports_enabled', models.BooleanField(default=False, verbose_name='Reportes Avanzados Habilitado')),
                ('advanced_promotions_enabled', models.BooleanField(default=False, verbose_name='Promociones Avanzadas Habilitado')),
                ('banners_enabled', models.BooleanField(default=False, verbose_name='Banners/Anuncios Habilitado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Paquete',
                'verbose_name_plural': 'Plantillas de Paquetes',
                'ordering': ['package_type'],
            },
        ),
        migrations.RunPython(
            remove_link_field_if_exists,
            reverse_remove_link_field,
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre que se mostrará en la plataforma', max_length=200, verbose_name='Nombre de la Franquicia')),
                ('slug', models.SlugField(help_text='URL amigable (ej: mi-franquicia)', max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la franquicia', null=True, upload_to='franchises/logos/', verbose_name='Logo')),
                ('image', models.ImageField(blank=True, help_text='Imagen principal de la franquicia', null=True, upload_to='franchises/images/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la franquicia está activa', verbose_name='Activa')),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio de Suscripción')),
                ('subscription_end_date', models.DateTimeField(blank=True, help_text='Si es None, la suscripción es indefinida', null=True, verbose_name='Fecha de Fin de Suscripción')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Precio mensual que paga esta franquicia', max_digits=10, verbose_name='Precio Mensual')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión que se cobra', max_digits=5, verbose_name='Tasa de Comisión (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(blank=True, help_text='Super admin que creó esta franquicia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_franchises', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('owner', models.OneToOneField(help_text='Usuario que administra esta franquicia', on_delete=django.db.models.deletion.CASCADE, related_name='owned_franchise', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('package_template', models.ForeignKey(help_text='Paquete que tiene contratado esta franquicia', on_delete=django.db.models.deletion.PROTECT, related_name='franchises', to='bingo_app.packagetemplate', verbose_name='Paquete Contratado')),
            ],
            options={
                'verbose_name': 'Franquicia',
                'verbose_name_plural': 'Franquicias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece esta cuenta bancaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece esta solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece este juego', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece esta rifa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='user',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece este usuario (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='franchise',
            field=models.ForeignKey(blank=True, help_text='Franquicia a la que pertenece esta solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='bingo_app.franchise', verbose_name='Franquicia'),
        ),
        migrations.CreateModel(
            name='FranchiseManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', help_text='Contenido HTML del manual personalizado', verbose_name='Contenido del Manual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='bingo_app.franchise', verbose_name='Franquicia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_manuals', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Manual de Franquicia',
                'verbose_name_plural': 'Manuales de Franquicias',
            },
        ),
    ]
