# Generated by Django 5.2.7 on 2025-12-14 16:08

from django.db import migrations, models


def remove_link_field_if_exists(apps, schema_editor):
    """
    Elimina el campo 'link' de Announcement solo si existe.
    Esto evita errores si el campo ya fue eliminado en una migración anterior.
    """
    db_alias = schema_editor.connection.alias
    try:
        with schema_editor.connection.cursor() as cursor:
            # Verificar si la columna existe
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='bingo_app_announcement' 
                AND column_name='link'
            """)
            if cursor.fetchone():
                # La columna existe, eliminarla usando SQL directo
                cursor.execute("ALTER TABLE bingo_app_announcement DROP COLUMN IF EXISTS link;")
    except Exception:
        # Si hay algún error, simplemente continuar
        # El campo probablemente ya no existe
        pass


def reverse_remove_link_field(apps, schema_editor):
    """
    Función reversa: no hace nada porque no queremos recrear el campo
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0053_packagetemplate_remove_announcement_link_franchise_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_link_field_if_exists,
            reverse_remove_link_field,
        ),
        migrations.AddField(
            model_name='raffle',
            name='multiple_winners_enabled',
            field=models.BooleanField(default=False, help_text='Si está activado, se seleccionarán múltiples ganadores con premios escalonados', verbose_name='Habilitar múltiples ganadores'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='prize_structure',
            field=models.JSONField(blank=True, default=list, help_text="Lista de premios escalonados. Ejemplo: [{'position': 1, 'prize': 1000}, {'position': 2, 'prize': 500}]", verbose_name='Estructura de premios'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winners',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ganadores con posición y premio asignado', verbose_name='Ganadores'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winning_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Lista de números ganadores en orden de posición', verbose_name='Números ganadores'),
        ),
    ]
