# Generated by Django 5.2.7 on 2025-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0053_packagetemplate_remove_announcement_link_franchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.AddField(
            model_name='raffle',
            name='multiple_winners_enabled',
            field=models.BooleanField(default=False, help_text='Si está activado, se seleccionarán múltiples ganadores con premios escalonados', verbose_name='Habilitar múltiples ganadores'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='prize_structure',
            field=models.JSONField(blank=True, default=list, help_text="Lista de premios escalonados. Ejemplo: [{'position': 1, 'prize': 1000}, {'position': 2, 'prize': 500}]", verbose_name='Estructura de premios'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winners',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ganadores con posición y premio asignado', verbose_name='Ganadores'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winning_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Lista de números ganadores en orden de posición', verbose_name='Números ganadores'),
        ),
    ]
