# Generated by Django 5.2.7 on 2025-12-14 20:48

from django.db import migrations, models


def remove_link_field_if_exists(apps, schema_editor):
    """Remove link field from Announcement if it exists"""
    db_alias = schema_editor.connection.alias
    try:
        schema_editor.execute("ALTER TABLE bingo_app_announcement DROP COLUMN IF EXISTS link;")
    except Exception as e:
        # Field doesn't exist, which is fine
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0054_add_multiple_winners_to_raffle'),
    ]

    operations = [
        migrations.RunPython(remove_link_field_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name='raffle',
            name='manual_winning_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Lista de números ganadores ingresados manualmente (para múltiples ganadores). Ejemplo: [45, 78, 12]', verbose_name='Números ganadores manuales'),
        ),
    ]
