# Generated by Django 5.2.7 on 2025-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0055_add_manual_winning_numbers_to_raffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.AddField(
            model_name='raffle',
            name='number_format_digits',
            field=models.PositiveIntegerField(default=0, help_text='Número de dígitos para mostrar los números (ej: 3 para 000, 001, 002...). 0 = sin formato', verbose_name='Dígitos para formato de números'),
        ),
    ]
