# Generated by Django 5.2.7 on 2025-12-14 23:42

from django.db import migrations, models


def remove_link_field_if_exists(apps, schema_editor):
    """Remove link field from Announcement if it exists"""
    db_alias = schema_editor.connection.alias
    try:
        schema_editor.execute("ALTER TABLE bingo_app_announcement DROP COLUMN IF EXISTS link;")
    except Exception as e:
        # Field doesn't exist, which is fine
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0056_add_number_format_digits_to_raffle'),
    ]

    operations = [
        migrations.RunPython(remove_link_field_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name='raffle',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto (ej: 1234567890 o link de grupo). Se mostrará un botón con el logo de WhatsApp', max_length=20, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
