# Generated by Django 5.2.7 on 2025-12-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0056_add_number_format_digits_to_raffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.AddField(
            model_name='raffle',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto (ej: 1234567890 o link de grupo). Se mostrará un botón con el logo de WhatsApp', max_length=20, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
