# Generated by Django 5.2.7 on 2025-12-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0057_add_whatsapp_number_to_raffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.AlterField(
            model_name='raffle',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para contacto (ej: 1234567890) o enlace de grupo (ej: https://chat.whatsapp.com/...). Se mostrará un botón con el logo de WhatsApp', max_length=200, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
