# Generated by Django 5.2.7 on 2025-12-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0059_add_whatsapp_to_game_and_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Dominio personalizado para esta franquicia (ej: mi-franquicia.com). Debe configurarse en el DNS apuntando a este servidor.', max_length=255, null=True, unique=True, verbose_name='Dominio Personalizado'),
        ),
    ]
