# Generated by Django 5.2.7 on 2025-12-23 17:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0060_add_custom_domain_to_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePremiumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('DICE_BATTLE', 'Dice Battle (Dados entre 3)')], default='DICE_BATTLE', max_length=50, verbose_name='Tipo de MÃ³dulo')),
                ('is_active', models.BooleanField(default=False, help_text='Si estÃ¡ activo, los usuarios de esta franquicia pueden ver y usar este mÃ³dulo', verbose_name='MÃ³dulo Activo para esta Franquicia')),
                ('purchased_at', models.DateTimeField(blank=True, help_text='CuÃ¡ndo se comprÃ³ este mÃ³dulo', null=True, verbose_name='Fecha de Compra')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Si tiene fecha de expiraciÃ³n, el mÃ³dulo se desactiva automÃ¡ticamente', null=True, verbose_name='Fecha de ExpiraciÃ³n')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio que pagÃ³ la franquicia por este mÃ³dulo', max_digits=10, verbose_name='Precio de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MÃ³dulo Premium de Franquicia',
                'verbose_name_plural': 'MÃ³dulos Premium de Franquicias',
            },
        ),
        migrations.CreateModel(
            name='DiceGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, help_text='CÃ³digo Ãºnico de la sala', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Esperando jugadores'), ('SPINNING', 'Determinando premio'), ('PLAYING', 'En juego'), ('FINISHED', 'Terminada')], db_index=True, default='WAITING', max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Precio que pagan los 3 jugadores para entrar a esta partida. MÃ\xadnimo: $0.10', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Precio de Entrada')),
                ('base_prize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Premio Base (sin multiplicador)')),
                ('multiplier', models.CharField(default='1x', help_text='Multiplicador aleatorio (2x, 3x, 100x, etc.)', max_length=10)),
                ('final_prize', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Premio Final (con multiplicador)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_dice_games', to=settings.AUTH_USER_MODEL, verbose_name='Ganador')),
            ],
            options={
                'verbose_name': 'Partida de Dados',
                'verbose_name_plural': 'Partidas de Dados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiceMatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=2, help_text='Precio que el jugador estÃ¡ dispuesto a pagar. MÃ\xadnimo: $0.10', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Precio de Entrada Deseado')),
                ('status', models.CharField(choices=[('WAITING', 'Esperando jugadores'), ('MATCHED', 'Emparejado - Creando partida'), ('TIMEOUT', 'Timeout - Cancelado')], default='WAITING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='Un usuario solo puede estar en la cola una vez', on_delete=django.db.models.deletion.CASCADE, related_name='dice_queue_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cola de Matchmaking',
                'verbose_name_plural': 'Colas de Matchmaking',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='DiceModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_module_enabled', models.BooleanField(default=False, help_text='Solo super administradores pueden activar este mÃ³dulo. Si estÃ¡ desactivado, el mÃ³dulo NO aparece en ninguna parte del sistema.', verbose_name='Activar MÃ³dulo de Dados')),
                ('base_entry_price', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Precio mÃ\xadnimo de entrada. Los organizadores pueden establecer precios mayores. MÃ\xadnimo: $0.10', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Precio de Entrada Base (MÃ\xadnimo)')),
                ('allow_custom_entry_price', models.BooleanField(default=True, help_text='Si estÃ¡ activo, los organizadores pueden establecer el precio de entrada manualmente para cada partida', verbose_name='Permitir Precio Personalizado')),
                ('max_entry_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio mÃ¡ximo permitido. Si estÃ¡ vacÃ\xado, no hay lÃ\xadmite mÃ¡ximo.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Precio MÃ¡ximo (Opcional)')),
                ('multiplier_probabilities', models.JSONField(default=dict, help_text="Probabilidades de cada multiplicador. Ej: {'2x': 0.60, '3x': 0.25, '100x': 0.002}")),
                ('max_players_per_game', models.PositiveIntegerField(default=3, help_text='Siempre debe ser 3', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)], verbose_name='Jugadores por Partida')),
                ('power_ups_enabled', models.BooleanField(default=False, help_text='Permitir compra de power-ups antes de la partida', verbose_name='Activar Power-Ups')),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje que se cobra del premio total', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))], verbose_name='ComisiÃ³n de Plataforma (%)')),
                ('show_in_lobby', models.BooleanField(default=True, help_text='Si estÃ¡ activo, muestra el botÃ³n en el lobby principal', verbose_name='Mostrar en Lobby')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Ãšltimo super admin que modificÃ³ esta configuraciÃ³n', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dice_module_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ConfiguraciÃ³n MÃ³dulo de Dados',
                'verbose_name_plural': 'ConfiguraciÃ³n MÃ³dulo de Dados',
            },
        ),
        migrations.CreateModel(
            name='DicePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eliminated', models.BooleanField(default=False)),
                ('lives', models.PositiveIntegerField(default=3, help_text='Vidas restantes')),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Puntos acumulados')),
                ('power_ups_used', models.JSONField(default=list, help_text='Lista de power-ups usados en esta partida')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_players', to='bingo_app.dicegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_player_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador de Dados',
                'verbose_name_plural': 'Jugadores de Dados',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.AddField(
            model_name='dicegame',
            name='players',
            field=models.ManyToManyField(help_text='Jugadores en esta partida', related_name='dice_games', through='bingo_app.DicePlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiceRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='NÃºmero de Ronda')),
                ('player_results', models.JSONField(default=dict, help_text='Dict con user_id: [dado1, dado2, suma]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eliminated_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminated_in_rounds', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='bingo_app.dicegame')),
            ],
            options={
                'verbose_name': 'Ronda de Dados',
                'verbose_name_plural': 'Rondas de Dados',
                'ordering': ['round_number'],
            },
        ),
    ]
