# Generated by Django 5.2.7 on 2025-12-23 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0061_franchisepremiummodule_remove_announcement_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicematchmakingqueue',
            name='user',
            field=models.ForeignKey(help_text='Jugador en la cola', on_delete=django.db.models.deletion.CASCADE, related_name='dice_queue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dicematchmakingqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'WAITING')), fields=('user',), name='unique_user_waiting_queue'),
        ),
    ]
