# Generated by Django 5.2.7 on 2025-12-26 19:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0062_fix_dice_matchmaking_queue_one_to_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.AddField(
            model_name='dicemodulesettings',
            name='accumulated_pool',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fondo acumulado para premios. Se carga con el 80% de las entradas y se descuenta al otorgar premios.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pozo Acumulado'),
        ),
    ]
